# Generated by Django 4.2 on 2023-04-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(default='write your story', max_length=200),
        ),
    ]
